import { readdir, stat } from "node:fs/promises";
import path from "node:path";
import { TopBar, SectionLabel } from "@/components/Chrome";
import { DEMO_PHOTOS, DEMO_DIR } from "@/lib/demoPhotos";
import { agencies, generatedFor } from "@/lib/data";

/**
 * The demo's back pocket.
 *
 * There is no database at runtime, which is the right call for a prototype and
 * an awkward one the moment somebody asks "so what is actually in the schema".
 * This page answers that without a laptop: every file seed.py touched, plus
 * the photos the scan runs on, downloadable from the live URL.
 *
 * Sizes are read off disk at build time rather than hardcoded, so regenerating
 * the seed cannot leave a stale number here.
 */

export const metadata = {
  title: "CareSpace data",
  description: "The synthetic dataset behind the demo.",
};

const DIR = "demo-data";

/** Hand-written because a file listing cannot say why a file matters. */
const BLURBS: Record<string, string> = {
  "carespace.db": "SQLite. The source of truth seed.py writes.",
  "schema.sql": "The DDL. Tables, the three views that do the arithmetic.",
  "CareSpace_Synthetic_DB.xlsx": "Same data as a workbook, one sheet per table.",
  "seed.py": "Writes the .db and fixture.json. No dependencies.",
  "export_xlsx.py": "Turns the .db into the workbook.",
  "README.md": "What is real, what is synthetic, and why cubic feet.",
};

const ORDER = [
  "carespace.db",
  "schema.sql",
  "CareSpace_Synthetic_DB.xlsx",
  "seed.py",
  "export_xlsx.py",
  "README.md",
];

function human(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${Math.round(bytes / 1024)} KB`;
  return `${(bytes / 1024 / 1024).toFixed(1)} MB`;
}

type Entry = { name: string; size: number };

async function listing(): Promise<{ files: Entry[]; photos: Entry[] }> {
  const dir = path.join(process.cwd(), "public", DIR);
  let names: string[];
  try {
    names = await readdir(dir);
  } catch {
    // public/demo-data is generated by prebuild. If a build skipped it the
    // page should still render rather than take the deploy down.
    return { files: [], photos: [] };
  }

  const entries = await Promise.all(
    names
      .filter((n) => !n.startsWith("."))
      .map(async (name) => ({
        name,
        size: (await stat(path.join(dir, name))).size,
      }))
  );

  const isPhoto = (n: string) => /\.jpe?g$/i.test(n);
  return {
    files: entries
      .filter((e) => !isPhoto(e.name))
      .sort((a, b) => {
        const ai = ORDER.indexOf(a.name);
        const bi = ORDER.indexOf(b.name);
        return (ai < 0 ? 99 : ai) - (bi < 0 ? 99 : bi);
      }),
    photos: entries.filter((e) => isPhoto(e.name)).sort((a, b) =>
      a.name.localeCompare(b.name)
    ),
  };
}

export default async function DataPage() {
  const { files, photos } = await listing();

  return (
    <main className="flex-1 flex flex-col">
      <TopBar back="/" title="Data" />

      <div className="px-5 py-4 border-b border-line">
        <p className="text-[13px] leading-relaxed text-muted">
          The demo runs off a bundled fixture, so nothing here is queried at
          runtime. This is the material it was generated from, kept downloadable
          so the schema is one tap away instead of on a laptop.
        </p>
        <p className="text-[11px] text-muted mt-2.5 leading-relaxed">
          Every site, measurement, and count is synthetic. Generated for{" "}
          {generatedFor}.
        </p>
      </div>

      <div className="px-5 py-5 border-b border-line">
        <SectionLabel>Database</SectionLabel>
        {files.length === 0 ? (
          <p className="text-[12.5px] text-muted">
            Not bundled in this build. Run{" "}
            <code className="text-[11.5px]">npm run build</code> from{" "}
            <code className="text-[11.5px]">app/</code> with{" "}
            <code className="text-[11.5px]">data/</code> alongside it.
          </p>
        ) : (
          <ul className="space-y-1.5">
            {files.map((f) => (
              <li key={f.name}>
                <a
                  href={`/${DIR}/${f.name}`}
                  download
                  className="flex items-baseline gap-2 rounded-lg border border-line px-3.5 py-2.5
                             hover:border-accent transition-colors"
                >
                  <span className="text-[13.5px] font-medium truncate">
                    {f.name}
                  </span>
                  <span className="text-[11px] text-muted tnum ml-auto shrink-0">
                    {human(f.size)}
                  </span>
                </a>
                {BLURBS[f.name] && (
                  <p className="text-[11.5px] text-muted mt-1 mb-2 px-0.5 leading-relaxed">
                    {BLURBS[f.name]}
                  </p>
                )}
              </li>
            ))}
          </ul>
        )}
      </div>

      <div className="px-5 py-5 border-b border-line">
        <SectionLabel>What the fixture holds</SectionLabel>
        <ul className="space-y-1">
          {agencies.map((a) => (
            <li
              key={a.id}
              className="flex items-baseline gap-2 text-[12.5px] py-1"
            >
              <span className="truncate">{a.name}</span>
              <span className="text-muted tnum ml-auto shrink-0">
                {a.boxes_today} boxes
              </span>
            </li>
          ))}
        </ul>
      </div>

      <div className="px-5 py-5">
        <SectionLabel>Scan photos</SectionLabel>
        <p className="text-[12px] text-muted mb-3 leading-relaxed">
          The eight the demo button loads, already downscaled. Originals below.
        </p>
        <div className="grid grid-cols-4 gap-1.5">
          {DEMO_PHOTOS.map((p) => (
            <a
              key={p.file}
              href={`${DEMO_DIR}/${p.file}`}
              download
              title={p.caption}
              className="relative aspect-square"
            >
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={`${DEMO_DIR}/${p.file}`}
                alt={p.caption}
                loading="lazy"
                className="w-full h-full object-cover rounded-lg border border-line"
              />
            </a>
          ))}
        </div>

        {photos.length > 0 && (
          <>
            <p className="text-[11.5px] text-muted mt-4 mb-2 leading-relaxed">
              Originals, straight off the phone.
            </p>
            <ul className="space-y-1">
              {photos.map((p) => (
                <li key={p.name}>
                  <a
                    href={`/${DIR}/${p.name}`}
                    download
                    className="flex items-baseline gap-2 text-[12px] py-1.5 hover:text-accent transition-colors"
                  >
                    <span className="truncate">{p.name}</span>
                    <span className="text-muted tnum ml-auto shrink-0">
                      {human(p.size)}
                    </span>
                  </a>
                </li>
              ))}
            </ul>
          </>
        )}
      </div>
    </main>
  );
}
