import fixture from "./fixture.json";

/**
 * Read-only accessors over the synthetic fixture.
 *
 * The fixture is generated by data/seed.py straight out of data/carespace.db,
 * so the shapes here match the SQLite schema. When the app moves onto the real
 * database, only this file changes.
 */

export type ZoneId = "shelf_stable" | "refrigerated";

export type ZoneCapacity = {
  zone_id: ZoneId;
  label: string;
  usable_cuft: number;
  cuft_per_box: number;
  /** Boxes this zone could hold if no other zone existed. */
  boxes_if_alone: number;
  /** The zone that runs out first, and therefore sets the whole site. */
  is_binding: boolean;
  /** Box slots in this zone that nothing can ever fill. */
  dead_boxes: number;
  dead_cuft: number;
  source: "scan" | "manual" | "override";
  measured_at: string | null;
};

export type StorageUnit = {
  id: string;
  zone_id: ZoneId;
  kind_id: string;
  kind_label: string;
  label: string;
  gross_cuft: number;
  usable_pct: number;
  source: "scan" | "manual" | "override";
  confidence: number | null;
  notes: string | null;
  measured_at: string;
};

export type InventoryRow = {
  name: string;
  category: string;
  zone_id: ZoneId;
  /** "25 lb bag", "case of 12 (15oz)". Units are not uniform, so a count of
   *  these is a count of items, never a count of cases. */
  unit_description: string;
  qty_units: number;
  unit_weight_lb: number;
  unit_volume_cuft: number;
  total_lb: number;
  total_cuft: number;
};

export type Distribution = {
  distributed_on: string;
  boxes_out: number;
  people_served: number;
  /** The column that says whose problem an under-used site is. */
  turned_away: number;
  notes: string | null;
};

export type Agency = {
  id: string;
  name: string;
  address: string;
  city: string;
  zip: string;
  service_type: string;
  food_category: string;
  distribution_day: string | null;
  frequency: string;
  is_hub: number;
  /** Pinned to the top of the picker so it is easy to find in a demo. */
  is_demo: number;
  story: string;
  zones: ZoneCapacity[];
  binding_zone: ZoneId;
  /** Complete boxes the site can hold right now. The min across zones. */
  boxes_today: number;
  people_fed_today: number;
  storage_units: StorageUnit[];
  inventory: InventoryRow[];
  /** Newest first. */
  distributions: Distribution[];
};

export type Operator = {
  id: string;
  name: string;
  role: "agency_rep" | "logistics_operator";
  agency_id: string | null;
  agency_name: string | null;
};

const data = fixture as unknown as {
  generated_for: string;
  box: {
    id: string;
    name: string;
    feeds_people: number;
    feeds_days: number;
    description: string;
    zone_demand: Record<ZoneId, { cuft_per_box: number; lb_per_box: number }>;
    lines: {
      name: string;
      zone_id: ZoneId;
      consumer_qty: string;
      unit_description: string;
      qty_units: number;
      unit_volume_cuft: number;
    }[];
  };
  zones: { id: ZoneId; label: string; temp_min_f: number; temp_max_f: number }[];
  storage_unit_kinds: {
    id: string;
    label: string;
    zone_id: ZoneId;
    typical_cuft: number;
    usable_default: number;
    is_fixed: number;
  }[];
  operators: Operator[];
  agencies: Agency[];
};

export const box = data.box;
export const zones = data.zones;
export const storageUnitKinds = data.storage_unit_kinds;
export const operators = data.operators;
export const agencies = data.agencies;
export const generatedFor = data.generated_for;

export function getAgency(id: string): Agency | undefined {
  return data.agencies.find((a) => a.id === id);
}

export function getOperator(id: string): Operator | undefined {
  return data.operators.find((o) => o.id === id);
}

export function kindsForZone(zone: ZoneId) {
  return data.storage_unit_kinds.filter((k) => k.zone_id === zone);
}

/**
 * What one more storage unit of this kind would unlock, in complete boxes.
 * Adding capacity to a zone that is not binding unlocks nothing, which is the
 * point worth showing.
 */
export function boxesUnlockedBy(agency: Agency, kindId: string): number {
  const kind = storageUnitKinds.find((k) => k.id === kindId);
  if (!kind) return 0;
  const gained = kind.typical_cuft * kind.usable_default;
  const after = agency.zones.map((z) =>
    z.zone_id === kind.zone_id
      ? Math.floor((z.usable_cuft + gained) / z.cuft_per_box)
      : z.boxes_if_alone
  );
  return Math.min(...after) - agency.boxes_today;
}

/** Cubic feet of each zone that one box consumes. */
export const zoneDemand: Record<ZoneId, number> = Object.fromEntries(
  Object.entries(data.box.zone_demand).map(([z, d]) => [z, d.cuft_per_box])
) as Record<ZoneId, number>;

/**
 * The only cubic-foot number the UI ever shows: what you can actually stack
 * into a unit. Gross size is an input to this and is never displayed on its
 * own, because two different numbers for one shelf reads as broken math.
 */
export const usableCuft = (u: { gross_cuft: number; usable_pct: number }) =>
  Math.round(u.gross_cuft * u.usable_pct);

/** People one box feeds for a week. Boxes are the unit of packing; people are
 *  the unit anyone actually cares about, so the UI counts in people. */
export const PEOPLE_PER_BOX = data.box.feeds_people;

export const toPeople = (boxes: number) => boxes * PEOPLE_PER_BOX;

export type EditableUnit = {
  id: string;
  zone_id: ZoneId;
  kind_id: string;
  kind_label: string;
  label: string;
  gross_cuft: number;
  usable_pct: number;
  confidence: number | null;
  /** false once a rep says this is not really there. */
  present: boolean;
  /** true for anything the rep added by hand after the scan. */
  added: boolean;
};

/**
 * People a set of storage units can feed for a week. A box is atomic, so this
 * is the minimum across zones and never the sum.
 */
export function peopleFromUnits(units: EditableUnit[]): {
  people: number;
  perZone: Record<ZoneId, { usable_cuft: number; people: number }>;
} {
  const perZone = {} as Record<ZoneId, { usable_cuft: number; people: number }>;
  for (const z of zones) {
    const cuft = units
      .filter((u) => u.present && u.zone_id === z.id)
      .reduce((s, u) => s + u.gross_cuft * u.usable_pct, 0);
    perZone[z.id] = {
      usable_cuft: cuft,
      people: toPeople(Math.floor(cuft / zoneDemand[z.id])),
    };
  }
  return {
    people: Math.min(...zones.map((z) => perZone[z.id].people)),
    perZone,
  };
}

/**
 * What the scan hunted for and did not find. Naming the things is the point:
 * "nothing found" reads like the scan gave up, and a rep cannot argue with it.
 */
export const ZONE_EMPTY_COPY: Record<ZoneId, string> = {
  shelf_stable: "No shelving, racking, or pantry space found.",
  refrigerated: "No cooler, fridge, or cold room found.",
};

/** "2026-08-14" -> "Aug 14". Parsed off the string so no timezone can shift it. */
export function shortDate(iso: string): string {
  const M = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
  const [, m, d] = iso.split("-");
  return `${M[Number(m) - 1]} ${Number(d)}`;
}

/**
 * Short adjective form, for sentences. The label is a noun phrase
 * ("Refrigerated Goods") and reads badly in "no ... storage at all".
 */
export const ZONE_ADJ: Record<ZoneId, string> = {
  shelf_stable: "shelf-stable",
  refrigerated: "refrigerated",
};

/**
 * Two zones, split warm and cool. Refrigerated borrows the brand teal; shelf-stable
 * takes an ochre so the pair reads as two categories rather than two shades.
 * Values live in globals.css so the palette stays in one place.
 */
export const ZONE_STYLE: Record<
  ZoneId,
  { bar: string; dot: string; text: string }
> = {
  shelf_stable: {
    bar: "bg-[var(--zone-shelf)]",
    dot: "bg-[var(--zone-shelf)]",
    text: "text-[var(--zone-shelf)]",
  },
  refrigerated: {
    bar: "bg-[var(--zone-refrigerated)]",
    dot: "bg-[var(--zone-refrigerated)]",
    text: "text-[var(--zone-refrigerated)]",
  },
};
